[package]
name = "ecom-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-mongodb-session = "3.0.0"
async-std = "1.12.0"
serde = "1.0.189"
tide = "0.16.0"
